backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "images/uploads"

collections:
  - name: "geral"
    label: "Informações do Site"
    files:
      - file: "content/geral.json"
        label: "Conteúdo Geral"
        name: "geral"

        fields:
          - { label: "Título do Site", name: "titulo", widget: "string" }
          - { label: "Descrição", name: "descricao", widget: "text" }

          - label: "Imagem Principal"
            name: "imagem"
            widget: "image"

          - label: "História"
            name: "historia"
            widget: "text"

          - label: "Pastores"
            name: "pastores"
            widget: "list"
            fields:
              - { label: "Nome", name: "nome", widget: "string" }
              - { label: "Cargo", name: "cargo", widget: "string" }
              - { label: "Foto", name: "foto", widget: "image" }

          - label: "Cultos"
            name: "cultos"
            widget: "list"
            fields:
              - { label: "Dia", name: "dia", widget: "string" }
              - { label: "Nome", name: "nome", widget: "string" }
              - { label: "Horário", name: "horario", widget: "string" }
